//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayActivity
    {
        public int Activity_Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Duration { get; set; }
    }
}
