//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalNote
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime System_Created { get; set; }
        public System.DateTime SystemUpdateDateTime { get; set; }
    }
}
